### PR TITLE
adding submodule to private icgm-sdk-ios repo

### PR DESCRIPTION
**Pull request by nhamming**
https://tidepool.atlassian.net/browse/LOOP-304

Adding the Dexcom provided frameworks as a submodule. User story scenarios can be found in the ticket as done criteria. If anything should be added or if I missed a step, let me know.

### CODE REVIEW

**Comment by nhamming** [comment]
> Loop development has always used a `master` and `dev` branch (unless Pete has changed things up recently). Would you mind moving this PR to a new `dev` branch and deleting the `staging` and `production` branches?
> 
> Also, let me know when you've done this and I can configure the repos according to Tidepool "standards". Thanks! (It is mostly https://docs.google.com/document/d/1FqM1zVqzTCjiL8WpXQNsdmLVo3riW2N5sRAAd64uDvs/edit with some modifications for Loop.)

Pete and I chatted about this recently, but maybe I missed the point. I'll replace `staging` with `dev` (which I think is a strange branch name since so development should happen in this branch) and I'll delete `production`. I'll make `dev` the default branch, since I don't see the value in making `master` the default branch, but correct me if I have a misunderstanding.

**Comment by nhamming** [comment]
Oh... forgot to add the I also think `master` is a cryptic branch name, even though it is in most repos. But I ask myself if it is `master` on purpose or is it because people just don't configure the repo such that pre-generated branch names are descriptive (e.g., such as `production`, `release`, etc.).

**Comment by ps2** [comment]
master and dev are pretty entrenched conventions at this point. Unless there is a compelling reason to switch, I think keeping them that way is best.

**Comment by nhamming** [comment]
Updated the PR and followed the configuration in `Tidepool GitHub Processes`.

**Comment by ps2** [comment]
The private sdk repo should have Dexcom in the name; iCGM is the generic FDA term for a "integrated CGM", and any sensors Tidepool Loop integrates with would likely have that designation.

**Comment by nhamming** [comment]
> The private sdk repo should have Dexcom in the name; iCGM is the generic FDA term for a "integrated CGM", and any sensors Tidepool Loop integrates with would likely have that designation.

Agree. I detected this in the naming of this repo. I just added Dexcom in the private repo name.

**Comment by ps2** [comment]
The name of this repo looks like dexcomi-cgm-kit. DexKit? DexcomCGMKit? Not sure we need the iCGM in the name of the repo; could put it in the description.

**Comment by nhamming** [comment]
> The name of this repo looks like dexcomi-cgm-kit. DexKit? DexcomCGMKit? Not sure we need the iCGM in the name of the repo; could put it in the description.

Yes, that is doable. 

Some rationale as to why I included iCGM in the title is that with just Dexcom, you don't really know what product you are targeting (remember I really like descriptive names). Is it the G5, G6, some other Dexcom product. I think iCGM clarifies this. 

That said, I'm not forcefully holding this position. Let me know if removing iCGM is still preferred and I'll do so.

**Comment by ps2** [comment]
A better capitalization scheme would be workable, too.

**Comment by ps2** [comment]
dexcom-icgm-loop-plugin?

**Comment by nhamming** [comment]
> dexcom-icgm-loop-plugin?

Will do. I assume this is for the private repo that includes the docs, frameworks, and sample app from Dexcom.

Any suggested updates for this repo name?

**Comment by nhamming** [comment]
after realizing I had a misunderstanding and talking to Pete, the repo is renamed to `dexcom-icgm-loop-plugin`

**Pull request merged**
